plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
}
//루트 프로젝트는 빌드 x

bootJar.enabled=false
jar.enabled=false

//하위 모듈에 주입할 내용들
subprojects{
    group = 'Codify'
    version = '0.0.1-SNAPSHOT'

    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories {
        mavenCentral()
    }

    ext {
        set('springCloudVersion', "2025.0.0")
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    //모든 서비스에서 공통으로 사용할 의존성
    dependencies {
//        implementation 'org.springframework.boot:spring-boot-starter-actuator'
//        implementation 'org.springframework.boot:spring-boot-starter-web'
//        compileOnly 'org.projectlombok:lombok'
//        developmentOnly 'org.springframework.boot:spring-boot-devtools'
//        annotationProcessor 'org.projectlombok:lombok'
//        testImplementation 'org.springframework.boot:spring-boot-starter-test'
//        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}

project(':assignment-service') {
    dependencies {
        implementation project(':codify-common')
    }
}

project(':parsing-service') {
    dependencies {
        implementation project(':codify-common')
    }
}

project(':query-service') {
    dependencies {
        implementation project(':codify-common')
    }
}

project(':similarity-service') {
    dependencies {
        implementation project(':codify-common')
    }
}

project(':submit-service') {
    dependencies {
        implementation project(':codify-common')
    }
}











